tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "inverse-primary": "#bcc7de",
                "primary": "#091426",
                "secondary-fixed-dim": "#b7c8e1",
                "on-surface": "#1b1b1d",
                "on-error": "#ffffff",
                "outline-variant": "#c5c6cd",
                "on-primary-fixed-variant": "#3c475a",
                "tertiary-container": "#35260c",
                "surface": "#fbf8fa",
                "on-secondary": "#ffffff",
                "tertiary-fixed-dim": "#ddc39d",
                "on-tertiary-fixed-variant": "#564427",
                "on-primary-fixed": "#111c2d",
                "on-secondary-fixed-variant": "#38485d",
                "background": "#fbf8fa",
                "surface-dim": "#dcd9db",
                "tertiary": "#1e1200",
                "on-surface-variant": "#45474c",
                "secondary-container": "#d0e1fb",
                "error-container": "#ffdad6",
                "inverse-surface": "#303032",
                "on-primary": "#ffffff",
                "on-background": "#1b1b1d",
                "surface-container-high": "#eae7e9",
                "surface-container": "#f0edef",
                "surface-container-low": "#f5f3f4",
                "on-tertiary": "#ffffff",
                "on-tertiary-container": "#a38c6a",
                "on-secondary-container": "#54647a",
                "primary-container": "#1e293b",
                "inverse-on-surface": "#f3f0f2",
                "on-tertiary-fixed": "#271902",
                "surface-variant": "#e4e2e3",
                "secondary": "#505f76",
                "on-primary-container": "#8590a6",
                "on-secondary-fixed": "#0b1c30",
                "error": "#ba1a1a",
                "surface-tint": "#545f73",
                "outline": "#75777d",
                "primary-fixed-dim": "#bcc7de",
                "surface-bright": "#fbf8fa",
                "secondary-fixed": "#d3e4fe",
                "on-error-container": "#93000a",
                "surface-container-lowest": "#ffffff",
                "primary-fixed": "#d8e3fb",
                "tertiary-fixed": "#fadfb8",
                "surface-container-highest": "#e4e2e3"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "container-max": "1280px",
                "margin-tablet": "32px",
                "gutter": "24px",
                "margin-mobile": "16px",
                "margin-desktop": "48px",
                "unit": "8px"
            },
            "fontFamily": {
                "body-sm": ["Inter"],
                "body-lg": ["Inter"],
                "label-md": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "label-sm": ["Inter"],
                "display-lg": ["Inter"],
                "headline-xl": ["Inter"],
                "body-md": ["Inter"],
                "headline-lg": ["Inter"]
            },
            "fontSize": {
                "body-sm": ["14px", {"lineHeight": "22px", "fontWeight": "400"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}],
                "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "500"}],
                "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-xl": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "26px", "letterSpacing": "0.01em", "fontWeight": "400"}],
                "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
            }
        },
    },
}
